defmodule Spector.Evented do
  @moduledoc """
  Mark a schema as evented, linking it to an event log table.

  ## Basic Usage

  ```elixir
  defmodule MyApp.User do
    use Spector.Evented, events: MyApp.Events
    use Ecto.Schema

    schema "users" do
      field :name, :string
    end

    def changeset(changeset, attrs) do
      changeset
      |> Ecto.Changeset.cast(attrs, [:name])
      |> Ecto.Changeset.validate_required([:name])
    end
  end
  ```

  ## Options

  * `:events` (required) - The events module (defined with `Spector.Events`)
  * `:repo` - Override the repo for this schema's table (default: uses events repo)
  * `:version` - Schema version for migrations (default: `0`). See "Schema Versioning" below
  * `:actions` - List of custom action atoms (default: `[]`). See "Custom Actions" below

  ## Custom Actions

  Beyond the built-in `:insert`, `:update`, and `:delete` actions, you can define
  custom actions for domain-specific operations:

  ```elixir
  defmodule MyApp.Item do
    use Spector.Evented,
      events: MyApp.Events,
      actions: [:archive, :restore]

    # Handle the archive action
    def changeset(changeset, attrs) when changeset.action == :archive do
      changeset
      |> Ecto.Changeset.change(archived_at: attrs[:archived_at])
    end

    # Handle other actions
    def changeset(changeset, attrs) do
      changeset
      |> Ecto.Changeset.cast(attrs, [:name, :value])
    end
  end
  ```

  Execute custom actions with `Spector.execute/3`:

  ```elixir
  {:ok, item} = Spector.execute(item, :archive, %{archived_at: DateTime.utc_now()})
  ```

  ## Schema Versioning

  When you change your schema (add/remove/rename fields), increment the version
  and handle migrations in your changeset:

  ```elixir
  defmodule MyApp.User do
    # Version 0: had :title field
    # Version 1: renamed :title to :name
    use Spector.Evented, events: MyApp.Events, version: 1

    schema "users" do
      field :name, :string
    end

    # Migrate v0 events (with :title) to v1 (with :name)
    def changeset(changeset, attrs) when version_is(attrs, 0) do
      attrs = Map.put(attrs, "name", attrs["title"])
      do_changeset(changeset, attrs)
    end

    def changeset(changeset, attrs), do: do_changeset(changeset, attrs)

    defp do_changeset(changeset, attrs) do
      changeset
      |> Ecto.Changeset.cast(attrs, [:name])
      |> Ecto.Changeset.validate_required([:name])
    end
  end
  ```

  The `version_is/2` and `version_in/2` guards help you handle different versions.
  When events are replayed, old events are passed through the changeset with their
  original version, allowing you to migrate data on the fly.

  ## Generated Functions

  Using this module generates:

  * `__spector__/1` - Internal metadata accessor
  * Imports `version_in/2` and `version_is/2` guards
  * Sets `@primary_key` to use UUIDv7 (non-autogenerated, as Spector manages IDs)
  """

  @doc """
  Guard to check if attrs version is within a range or list of integers.

  Example: `def changeset(struct, attrs) when version_in(attrs, 0..2)`
  """
  defmacro version_in(attrs, range) do
    quote do
      (is_map_key(unquote(attrs), "version") and (:erlang.map_get("version", unquote(attrs)) in unquote(range))) or
      (is_map_key(unquote(attrs), :version) and (:erlang.map_get(:version, unquote(attrs)) in unquote(range)))
    end
  end

  @doc """
  Guard to check if attrs version equals a specific integer.

  Example: `def changeset(struct, attrs) when version_is(attrs, 0)`
  """
  defmacro version_is(attrs, version) do
    quote do
      (is_map_key(unquote(attrs), "version") and :erlang.map_get("version", unquote(attrs)) == unquote(version)) or
        (is_map_key(unquote(attrs), :version) and :erlang.map_get(:version, unquote(attrs)) == unquote(version))
    end
  end

  defmacro __using__(opts) do
    events = Keyword.fetch!(opts, :events)
    repo = Keyword.get(opts, :repo)
    version = Keyword.get(opts, :version, 0)
    actions = Keyword.get(opts, :actions, [])

    quote do
      import Spector.Evented, only: [version_in: 2, version_is: 2]

      @primary_key {:id, UUIDv7, autogenerate: false}

      def __spector__(:events), do: unquote(events)
      def __spector__(:repo), do: unquote(repo)
      def __spector__(:version), do: unquote(version)
      def __spector__(:actions), do: unquote(actions)
    end
  end
end
